version: '3.9'

services:

  api:
    build:
      context: ../
      dockerfile: ./docker/api/Dockerfile
    network_mode: "host"
    tty: true
    depends_on:
      - db 

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: drinkbase
    volumes:
      - "./database/data:/docker-entrypoint-initdb.d"
    network_mode: "host"
 
  nodejs:
    build:
      context: ../
      dockerfile: ./docker/nodejs/Dockerfile
    tty: true
    volumes:
      - "/opt/drinkbase/build/:/builder/build"

  frontend:
    image: nginx:1.19
    volumes:
      - "/opt/drinkbase/build/:/drinkbase"
      - "${HOMEDIR}/docker/nginx/conf:/etc/nginx/conf.d"
      - "${HOMEDIR}/docker/nginx/scripts:/docker-entrypoint.d"
    network_mode: "host"
    tty: true
    depends_on:
      - db
      - api
