version: '3.1'

services:
  
  # postgresql
  database:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: drinkbase
    volumes:
      - "./postgresql/data:/docker-entrypoint-initdb.d"
    ports: 
      - 5432:5432

  # flask-apache
  api:
    build:
      context: ../
      dockerfile: ./docker/api/Dockerfile
    tty: true
    ports:
      - 8080:80
