version: '3.1'

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: drinkbase
    volumes:
      - "./postgresql/data:/docker-entrypoint-initdb.d"
    ports: 
      - 5432:5432
  api:
    build:
      context: ./api
    volumes:
      - "./api/conf/ports.conf:/etc/apache2/ports.conf"
      - "./api/conf/apache2.conf:/etc/apache2/apache2.conf"
      - "./api/conf/drinkbase.conf:/etc/apache2/sites-available/drinkbase.conf"
      - "../backend/src/:/home/debian/drinkbase/"
    tty: true
    ports:
      - 8080:80
