version: '3.9'

services:

  api:
    build:
      context: ../
      dockerfile: ./docker/api/Dockerfile
    network_mode: "host"
    tty: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    depends_on:
      - db 

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: drinkbase
    volumes:
      - "./postgresql/data:/docker-entrypoint-initdb.d"
    network_mode: "host"
