version: '3.9'

services:

  api:
    build:
      context: ../
      dockerfile: ./docker/api/Dockerfile
    network_mode: "host"
    tty: true
    depends_on:
      - db 

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: drinkbase
    volumes:
      - "./database/data:/docker-entrypoint-initdb.d"
    network_mode: "host"

  frontend:
    image: nginx:1.19
    volumes:
      - "${HOMEDIR}/frontend/build:/drinkbase"
      - "${HOMEDIR}/docker/nginx/scripts:/docker-entrypoint.d"
    ports:
      - "80:80"
      - "443:443"
    tty: true
    depends_on:
      - db
      - api
