version: '3.1'

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: drinkbase
    volumes:
      - "./postgresql/data:/docker-entrypoint-initdb.d"
    ports: 
      - 5432:5432

